main: com.cavetale.endergolf.EndergolfPlugin
name: Endergolf

version: ${version}
api-version: '1.21'

author: StarTux
website: https://github.com/StarTux/Endergolf
description: Endergolf Plugin

depend:
- Core
- Mytems
- Creative
- Area

softdepend: []

commands:

  endergolf:
    aliases: [golf]
    description: Endergolf Command
    permission: endergolf.endergolf
    usage: |-
      /endergolf

  endergolfadmin:
    aliases: [golfadm]
    description: Endergolf Admin Command
    permission: endergolf.admin
    usage: |-
      /endergolfadmin

permissions:

  endergolf.endergolf:
    description: Use /endergolf
    default: op

  endergolf.admin:
    description: Use /endergolfadmin
    default: op
